# remote_theme: chrisrhymes/bulma-clean-theme

theme: jekyll-theme-cayman
title: Event Recommendation Engine
description: A short description of your site's purpose
show_downloads: false
github:
  is_project_page: false
