# remote_theme: chrisrhymes/bulma-clean-theme

theme: jekyll-theme-cayman
title: Ramya Sree Boppana, Yuzi Hu, Vidhi Jindal, Pruthvi Perumalla
description: A short description of your site's purpose
show_downloads: false
github:
  is_project_page: false
