# remote_theme: chrisrhymes/bulma-clean-theme

theme: jekyll-theme-cayman
title: Event Recommendation Engine
description: Ramya Sree Boppana, Yuzi Hu, Vidhi Jindal, Pruthvi Perumalla
show_downloads: false
github:
  is_project_page: false
